name: RestrictOutsideBorder
version: ${version}
author: RunQ
main: com.nekozouneko.restrictOutsideBorder.RestrictOutsideBorder
api-version: '1.21'

folia-supported: true

commands:
  robreload:
    permission: rob.reload

permissions:
  rob.reload:
    default: op
  rob.bypass:
    default: op